// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/GolZrd/micro-chat/auth/internal/repository/access.AccessRepository -o access_repository_minimock.go -n AccessRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AccessRepositoryMock implements mm_access.AccessRepository
type AccessRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcEndPointRoles func(ctx context.Context, endPoint string) (m1 map[string]struct {
	}, err error)
	funcEndPointRolesOrigin    string
	inspectFuncEndPointRoles   func(ctx context.Context, endPoint string)
	afterEndPointRolesCounter  uint64
	beforeEndPointRolesCounter uint64
	EndPointRolesMock          mAccessRepositoryMockEndPointRoles
}

// NewAccessRepositoryMock returns a mock for mm_access.AccessRepository
func NewAccessRepositoryMock(t minimock.Tester) *AccessRepositoryMock {
	m := &AccessRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.EndPointRolesMock = mAccessRepositoryMockEndPointRoles{mock: m}
	m.EndPointRolesMock.callArgs = []*AccessRepositoryMockEndPointRolesParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAccessRepositoryMockEndPointRoles struct {
	optional           bool
	mock               *AccessRepositoryMock
	defaultExpectation *AccessRepositoryMockEndPointRolesExpectation
	expectations       []*AccessRepositoryMockEndPointRolesExpectation

	callArgs []*AccessRepositoryMockEndPointRolesParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccessRepositoryMockEndPointRolesExpectation specifies expectation struct of the AccessRepository.EndPointRoles
type AccessRepositoryMockEndPointRolesExpectation struct {
	mock               *AccessRepositoryMock
	params             *AccessRepositoryMockEndPointRolesParams
	paramPtrs          *AccessRepositoryMockEndPointRolesParamPtrs
	expectationOrigins AccessRepositoryMockEndPointRolesExpectationOrigins
	results            *AccessRepositoryMockEndPointRolesResults
	returnOrigin       string
	Counter            uint64
}

// AccessRepositoryMockEndPointRolesParams contains parameters of the AccessRepository.EndPointRoles
type AccessRepositoryMockEndPointRolesParams struct {
	ctx      context.Context
	endPoint string
}

// AccessRepositoryMockEndPointRolesParamPtrs contains pointers to parameters of the AccessRepository.EndPointRoles
type AccessRepositoryMockEndPointRolesParamPtrs struct {
	ctx      *context.Context
	endPoint *string
}

// AccessRepositoryMockEndPointRolesResults contains results of the AccessRepository.EndPointRoles
type AccessRepositoryMockEndPointRolesResults struct {
	m1 map[string]struct {
	}
	err error
}

// AccessRepositoryMockEndPointRolesOrigins contains origins of expectations of the AccessRepository.EndPointRoles
type AccessRepositoryMockEndPointRolesExpectationOrigins struct {
	origin         string
	originCtx      string
	originEndPoint string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) Optional() *mAccessRepositoryMockEndPointRoles {
	mmEndPointRoles.optional = true
	return mmEndPointRoles
}

// Expect sets up expected params for AccessRepository.EndPointRoles
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) Expect(ctx context.Context, endPoint string) *mAccessRepositoryMockEndPointRoles {
	if mmEndPointRoles.mock.funcEndPointRoles != nil {
		mmEndPointRoles.mock.t.Fatalf("AccessRepositoryMock.EndPointRoles mock is already set by Set")
	}

	if mmEndPointRoles.defaultExpectation == nil {
		mmEndPointRoles.defaultExpectation = &AccessRepositoryMockEndPointRolesExpectation{}
	}

	if mmEndPointRoles.defaultExpectation.paramPtrs != nil {
		mmEndPointRoles.mock.t.Fatalf("AccessRepositoryMock.EndPointRoles mock is already set by ExpectParams functions")
	}

	mmEndPointRoles.defaultExpectation.params = &AccessRepositoryMockEndPointRolesParams{ctx, endPoint}
	mmEndPointRoles.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmEndPointRoles.expectations {
		if minimock.Equal(e.params, mmEndPointRoles.defaultExpectation.params) {
			mmEndPointRoles.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmEndPointRoles.defaultExpectation.params)
		}
	}

	return mmEndPointRoles
}

// ExpectCtxParam1 sets up expected param ctx for AccessRepository.EndPointRoles
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) ExpectCtxParam1(ctx context.Context) *mAccessRepositoryMockEndPointRoles {
	if mmEndPointRoles.mock.funcEndPointRoles != nil {
		mmEndPointRoles.mock.t.Fatalf("AccessRepositoryMock.EndPointRoles mock is already set by Set")
	}

	if mmEndPointRoles.defaultExpectation == nil {
		mmEndPointRoles.defaultExpectation = &AccessRepositoryMockEndPointRolesExpectation{}
	}

	if mmEndPointRoles.defaultExpectation.params != nil {
		mmEndPointRoles.mock.t.Fatalf("AccessRepositoryMock.EndPointRoles mock is already set by Expect")
	}

	if mmEndPointRoles.defaultExpectation.paramPtrs == nil {
		mmEndPointRoles.defaultExpectation.paramPtrs = &AccessRepositoryMockEndPointRolesParamPtrs{}
	}
	mmEndPointRoles.defaultExpectation.paramPtrs.ctx = &ctx
	mmEndPointRoles.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmEndPointRoles
}

// ExpectEndPointParam2 sets up expected param endPoint for AccessRepository.EndPointRoles
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) ExpectEndPointParam2(endPoint string) *mAccessRepositoryMockEndPointRoles {
	if mmEndPointRoles.mock.funcEndPointRoles != nil {
		mmEndPointRoles.mock.t.Fatalf("AccessRepositoryMock.EndPointRoles mock is already set by Set")
	}

	if mmEndPointRoles.defaultExpectation == nil {
		mmEndPointRoles.defaultExpectation = &AccessRepositoryMockEndPointRolesExpectation{}
	}

	if mmEndPointRoles.defaultExpectation.params != nil {
		mmEndPointRoles.mock.t.Fatalf("AccessRepositoryMock.EndPointRoles mock is already set by Expect")
	}

	if mmEndPointRoles.defaultExpectation.paramPtrs == nil {
		mmEndPointRoles.defaultExpectation.paramPtrs = &AccessRepositoryMockEndPointRolesParamPtrs{}
	}
	mmEndPointRoles.defaultExpectation.paramPtrs.endPoint = &endPoint
	mmEndPointRoles.defaultExpectation.expectationOrigins.originEndPoint = minimock.CallerInfo(1)

	return mmEndPointRoles
}

// Inspect accepts an inspector function that has same arguments as the AccessRepository.EndPointRoles
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) Inspect(f func(ctx context.Context, endPoint string)) *mAccessRepositoryMockEndPointRoles {
	if mmEndPointRoles.mock.inspectFuncEndPointRoles != nil {
		mmEndPointRoles.mock.t.Fatalf("Inspect function is already set for AccessRepositoryMock.EndPointRoles")
	}

	mmEndPointRoles.mock.inspectFuncEndPointRoles = f

	return mmEndPointRoles
}

// Return sets up results that will be returned by AccessRepository.EndPointRoles
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) Return(m1 map[string]struct {
}, err error) *AccessRepositoryMock {
	if mmEndPointRoles.mock.funcEndPointRoles != nil {
		mmEndPointRoles.mock.t.Fatalf("AccessRepositoryMock.EndPointRoles mock is already set by Set")
	}

	if mmEndPointRoles.defaultExpectation == nil {
		mmEndPointRoles.defaultExpectation = &AccessRepositoryMockEndPointRolesExpectation{mock: mmEndPointRoles.mock}
	}
	mmEndPointRoles.defaultExpectation.results = &AccessRepositoryMockEndPointRolesResults{m1, err}
	mmEndPointRoles.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmEndPointRoles.mock
}

// Set uses given function f to mock the AccessRepository.EndPointRoles method
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) Set(f func(ctx context.Context, endPoint string) (m1 map[string]struct {
}, err error)) *AccessRepositoryMock {
	if mmEndPointRoles.defaultExpectation != nil {
		mmEndPointRoles.mock.t.Fatalf("Default expectation is already set for the AccessRepository.EndPointRoles method")
	}

	if len(mmEndPointRoles.expectations) > 0 {
		mmEndPointRoles.mock.t.Fatalf("Some expectations are already set for the AccessRepository.EndPointRoles method")
	}

	mmEndPointRoles.mock.funcEndPointRoles = f
	mmEndPointRoles.mock.funcEndPointRolesOrigin = minimock.CallerInfo(1)
	return mmEndPointRoles.mock
}

// When sets expectation for the AccessRepository.EndPointRoles which will trigger the result defined by the following
// Then helper
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) When(ctx context.Context, endPoint string) *AccessRepositoryMockEndPointRolesExpectation {
	if mmEndPointRoles.mock.funcEndPointRoles != nil {
		mmEndPointRoles.mock.t.Fatalf("AccessRepositoryMock.EndPointRoles mock is already set by Set")
	}

	expectation := &AccessRepositoryMockEndPointRolesExpectation{
		mock:               mmEndPointRoles.mock,
		params:             &AccessRepositoryMockEndPointRolesParams{ctx, endPoint},
		expectationOrigins: AccessRepositoryMockEndPointRolesExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmEndPointRoles.expectations = append(mmEndPointRoles.expectations, expectation)
	return expectation
}

// Then sets up AccessRepository.EndPointRoles return parameters for the expectation previously defined by the When method
func (e *AccessRepositoryMockEndPointRolesExpectation) Then(m1 map[string]struct {
}, err error) *AccessRepositoryMock {
	e.results = &AccessRepositoryMockEndPointRolesResults{m1, err}
	return e.mock
}

// Times sets number of times AccessRepository.EndPointRoles should be invoked
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) Times(n uint64) *mAccessRepositoryMockEndPointRoles {
	if n == 0 {
		mmEndPointRoles.mock.t.Fatalf("Times of AccessRepositoryMock.EndPointRoles mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmEndPointRoles.expectedInvocations, n)
	mmEndPointRoles.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmEndPointRoles
}

func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) invocationsDone() bool {
	if len(mmEndPointRoles.expectations) == 0 && mmEndPointRoles.defaultExpectation == nil && mmEndPointRoles.mock.funcEndPointRoles == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmEndPointRoles.mock.afterEndPointRolesCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmEndPointRoles.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// EndPointRoles implements mm_access.AccessRepository
func (mmEndPointRoles *AccessRepositoryMock) EndPointRoles(ctx context.Context, endPoint string) (m1 map[string]struct {
}, err error) {
	mm_atomic.AddUint64(&mmEndPointRoles.beforeEndPointRolesCounter, 1)
	defer mm_atomic.AddUint64(&mmEndPointRoles.afterEndPointRolesCounter, 1)

	mmEndPointRoles.t.Helper()

	if mmEndPointRoles.inspectFuncEndPointRoles != nil {
		mmEndPointRoles.inspectFuncEndPointRoles(ctx, endPoint)
	}

	mm_params := AccessRepositoryMockEndPointRolesParams{ctx, endPoint}

	// Record call args
	mmEndPointRoles.EndPointRolesMock.mutex.Lock()
	mmEndPointRoles.EndPointRolesMock.callArgs = append(mmEndPointRoles.EndPointRolesMock.callArgs, &mm_params)
	mmEndPointRoles.EndPointRolesMock.mutex.Unlock()

	for _, e := range mmEndPointRoles.EndPointRolesMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.err
		}
	}

	if mmEndPointRoles.EndPointRolesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmEndPointRoles.EndPointRolesMock.defaultExpectation.Counter, 1)
		mm_want := mmEndPointRoles.EndPointRolesMock.defaultExpectation.params
		mm_want_ptrs := mmEndPointRoles.EndPointRolesMock.defaultExpectation.paramPtrs

		mm_got := AccessRepositoryMockEndPointRolesParams{ctx, endPoint}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmEndPointRoles.t.Errorf("AccessRepositoryMock.EndPointRoles got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmEndPointRoles.EndPointRolesMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.endPoint != nil && !minimock.Equal(*mm_want_ptrs.endPoint, mm_got.endPoint) {
				mmEndPointRoles.t.Errorf("AccessRepositoryMock.EndPointRoles got unexpected parameter endPoint, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmEndPointRoles.EndPointRolesMock.defaultExpectation.expectationOrigins.originEndPoint, *mm_want_ptrs.endPoint, mm_got.endPoint, minimock.Diff(*mm_want_ptrs.endPoint, mm_got.endPoint))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmEndPointRoles.t.Errorf("AccessRepositoryMock.EndPointRoles got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmEndPointRoles.EndPointRolesMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmEndPointRoles.EndPointRolesMock.defaultExpectation.results
		if mm_results == nil {
			mmEndPointRoles.t.Fatal("No results are set for the AccessRepositoryMock.EndPointRoles")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmEndPointRoles.funcEndPointRoles != nil {
		return mmEndPointRoles.funcEndPointRoles(ctx, endPoint)
	}
	mmEndPointRoles.t.Fatalf("Unexpected call to AccessRepositoryMock.EndPointRoles. %v %v", ctx, endPoint)
	return
}

// EndPointRolesAfterCounter returns a count of finished AccessRepositoryMock.EndPointRoles invocations
func (mmEndPointRoles *AccessRepositoryMock) EndPointRolesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEndPointRoles.afterEndPointRolesCounter)
}

// EndPointRolesBeforeCounter returns a count of AccessRepositoryMock.EndPointRoles invocations
func (mmEndPointRoles *AccessRepositoryMock) EndPointRolesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEndPointRoles.beforeEndPointRolesCounter)
}

// Calls returns a list of arguments used in each call to AccessRepositoryMock.EndPointRoles.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmEndPointRoles *mAccessRepositoryMockEndPointRoles) Calls() []*AccessRepositoryMockEndPointRolesParams {
	mmEndPointRoles.mutex.RLock()

	argCopy := make([]*AccessRepositoryMockEndPointRolesParams, len(mmEndPointRoles.callArgs))
	copy(argCopy, mmEndPointRoles.callArgs)

	mmEndPointRoles.mutex.RUnlock()

	return argCopy
}

// MinimockEndPointRolesDone returns true if the count of the EndPointRoles invocations corresponds
// the number of defined expectations
func (m *AccessRepositoryMock) MinimockEndPointRolesDone() bool {
	if m.EndPointRolesMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.EndPointRolesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.EndPointRolesMock.invocationsDone()
}

// MinimockEndPointRolesInspect logs each unmet expectation
func (m *AccessRepositoryMock) MinimockEndPointRolesInspect() {
	for _, e := range m.EndPointRolesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccessRepositoryMock.EndPointRoles at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterEndPointRolesCounter := mm_atomic.LoadUint64(&m.afterEndPointRolesCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.EndPointRolesMock.defaultExpectation != nil && afterEndPointRolesCounter < 1 {
		if m.EndPointRolesMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccessRepositoryMock.EndPointRoles at\n%s", m.EndPointRolesMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccessRepositoryMock.EndPointRoles at\n%s with params: %#v", m.EndPointRolesMock.defaultExpectation.expectationOrigins.origin, *m.EndPointRolesMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcEndPointRoles != nil && afterEndPointRolesCounter < 1 {
		m.t.Errorf("Expected call to AccessRepositoryMock.EndPointRoles at\n%s", m.funcEndPointRolesOrigin)
	}

	if !m.EndPointRolesMock.invocationsDone() && afterEndPointRolesCounter > 0 {
		m.t.Errorf("Expected %d calls to AccessRepositoryMock.EndPointRoles at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.EndPointRolesMock.expectedInvocations), m.EndPointRolesMock.expectedInvocationsOrigin, afterEndPointRolesCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AccessRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockEndPointRolesInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AccessRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AccessRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockEndPointRolesDone()
}
